#!/bin/bash

if [ "$BUILDKITE_COMMAND_EXIT_STATUS" = "0" ]; then
  echo "command exited 0; exiting"
  exit 0
fi

if_condition="$BUILDKITE_PLUGIN_FAIL_FAST_IF"

if [ -n "$if_condition" ]; then
  if [[ "$if_condition" =~ \] ]]; then
    echo "'if' condition cannot contain brackets; exiting"
    exit 0
  fi

  if eval "[ $if_condition ]"; then
    echo "'if' condition evaluated true; continuing"
  else
    echo "'if' condition evaluated false; exiting"
    exit 0
  fi
fi

build_number="${BUILDKITE_TRIGGERED_FROM_BUILD_NUMBER:-$BUILDKITE_BUILD_NUMBER}"
org="$BUILDKITE_ORGANIZATION_SLUG"
pipeline="${BUILDKITE_TRIGGERED_FROM_BUILD_PIPELINE_SLUG:-$BUILDKITE_PIPELINE_SLUG}"
api_token="${BUILDKITE_TOKEN:-$BUILDKITE_AGENT_ACCESS_TOKEN}"

if [ -z "$build_number" ]; then
  echo "unable to find a build to cancel; exiting"
  exit 0
fi

curl -s "https://api.buildkite.com/v2/organizations/${org}/pipelines/${pipeline}/builds/$build_number/cancel" \
  -X PUT \
  -H "Authorization: Bearer $api_token"
